const DEFAULT_DOCUMENT_ATTRIBUTION = 'Generated by UHADEV | Custom Business Systems';

export const getDocumentAttributionText = (): string => {
  const value = process.env.PDF_DOCUMENT_ATTRIBUTION?.trim();
  return value || DEFAULT_DOCUMENT_ATTRIBUTION;
};

export const getDocumentAttributionHeight = (
  doc: PDFKit.PDFDocument,
  width: number
): number => {
  return doc.font('Helvetica').fontSize(7).heightOfString(getDocumentAttributionText(), {
    width,
    align: 'center'
  });
};

export const renderDocumentAttribution = (
  doc: PDFKit.PDFDocument,
  options?: {
    left?: number;
    width?: number;
    y?: number;
  }
): void => {
  const left = options?.left ?? doc.page.margins.left;
  const width = options?.width ?? doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const height = getDocumentAttributionHeight(doc, width);
  const y = options?.y ?? (doc.page.height - doc.page.margins.bottom - height);

  doc
    .font('Helvetica')
    .fontSize(7)
    .fillColor('#9ca3af')
    .text(getDocumentAttributionText(), left, y, { width, align: 'center' });
};
